-- Content Library (Tier 1 result page and PDF): every section text is a row
-- with a trigger, selected at render time — editable without a deployment.
-- Seed with database/seed/tier1-content.sql (generated by
-- `npm run seed:content` from database/seed/tier1-content.json).
CREATE TABLE IF NOT EXISTS content_piece (
  id           VARCHAR(64)  NOT NULL,
  section      VARCHAR(32)  NOT NULL,
  note_type    VARCHAR(8)   NULL,
  priority     INT          NOT NULL,
  trigger_expr TEXT         NOT NULL,
  heading      TEXT         NULL,
  body         TEXT         NOT NULL,
  active       BOOLEAN      NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  INDEX content_piece_section (section)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
