/**
 * Writes database/seed/tier1-content.sql from database/seed/tier1-content.json
 * — paste it into phpMyAdmin, or pass --apply to run it against DATABASE_URL.
 *
 * INSERT IGNORE: new pieces are added, existing rows are left alone, so
 * wording edited in the table is never overwritten by a re-seed.
 *
 * Usage: npm run seed:content [-- --apply]
 */
import { readFileSync, writeFileSync } from "node:fs";
import mysql from "mysql2/promise";

const { pieces } = JSON.parse(
  readFileSync(new URL("../database/seed/tier1-content.json", import.meta.url), "utf8"),
);

const sql = (value) =>
  value === null || value === undefined
    ? "NULL"
    : typeof value === "number"
      ? String(value)
      : `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n")}'`;

const rows = pieces.map((p) =>
  `  (${[p.id, p.section, p.note_type ?? null, p.priority, p.trigger, p.heading ?? null, p.body]
    .map(sql)
    .join(", ")}, ${p.active === false ? "FALSE" : "TRUE"})`,
);

const output = `-- Content Library v1.7 — generated by \`npm run seed:content\`; do not edit by hand.
-- Requires database/migrations/002_content_piece.sql. Re-running adds new pieces
-- and leaves existing (possibly edited) rows untouched.
SET NAMES utf8mb4;
INSERT IGNORE INTO content_piece
  (id, section, note_type, priority, trigger_expr, heading, body, active)
VALUES
${rows.join(",\n")};
`;

const target = new URL("../database/seed/tier1-content.sql", import.meta.url);
writeFileSync(target, output);
console.log(`Wrote ${pieces.length} pieces to database/seed/tier1-content.sql.`);

if (process.argv.includes("--apply")) {
  process.loadEnvFile?.(".env.local");
  if (!process.env.DATABASE_URL) process.loadEnvFile?.(".env");
  if (!process.env.DATABASE_URL) {
    console.error("DATABASE_URL is not set.");
    process.exit(1);
  }
  const db = await mysql.createConnection({ uri: process.env.DATABASE_URL, multipleStatements: true });
  try {
    const [result] = await db.query(output);
    const inserted = Array.isArray(result) ? result.at(-1).affectedRows : result.affectedRows;
    console.log(`Inserted ${inserted} new pieces (existing rows left unchanged).`);
  } finally {
    await db.end();
  }
}
